# Site settings
title: Even a Stopped Clock
description: >- # site description
  Random musings of a semi-sane designer from lesser Europe.
lang: en-US # default lang
timezone: Europe/Prague # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Jakub Steiner # author name
  bio: >- # tell to the world
    Musings of a visual designer from the lesser Europe
  username: jimmac # general username
  github: jimmac # github username
  twitter: jimmac # twitter username
  #facebook: facebook_username # facebook username
  email: jimmac@gmail.com # email adress
  avatar: /assets/img/avatar.svg # change with your own avatar

# URL settings
site_url: "https://blog.jimmac.eu" #
url: "https://blog.jimmac.eu" #
baseurl: /
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
